# Generated by Django 3.2.4 on 2021-06-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_convite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='solitante',
            new_name='solicitante',
        ),
    ]
