# Generated by Django 3.2.4 on 2021-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_rename_solitante_convite_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfis_perfil_contatos_+', to='perfis.Perfil'),
        ),
    ]
